version: '3.8'

services:
  magic-page-wiz:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUPPETEER_SKIP_DOWNLOAD=true
      - PUPPETEER_HEADLESS=true
    env_file:
      - .env
    volumes:
      - ./public/produtos:/app/public/produtos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  produtos_data: