services:
  # Backend API Service
  - type: web
    name: magic-page-wiz-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add your environment variables here
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_HOST
        sync: false
      - key: SHOPIFY_REDIRECT_URI
        sync: false
      - key: CJ_ACCESS_KEY
        sync: false
      - key: CJ_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # Frontend React App Service  
  - type: web
    name: magic-page-wiz-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /api/*
        destination: https://magic-page-wiz-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

# Database (if needed in the future)
# - type: pserv
#   name: magic-page-wiz-db
#   env: postgres
#   plan: free
#   databaseName: magicpagewiz
#   user: magicpagewiz